import "@/styles/globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white text-slate-900 dark:bg-slate-900 dark:text-slate-200 print:!text-black">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
